#Q1.1
SELECT _REGION.NAME AS 'REGION',_YEAR.NAME AS 'YEAR', SUM(REVENUE.VALUE) FROM REFERENCE_OBJECT RO
INNER JOIN REFERENCE_OBJECT_COMBINATION _RO_MONTH ON _RO_MONTH.COMBINATION_ID = RO.ID
INNER JOIN REFERENCE_OBJECT _MONTH ON _MONTH.ID = _RO_MONTH.SUBORDINATE_ID AND _MONTH.DIMENSION_ID = 18
INNER JOIN REFERENCE_OBJECT_COMBINATION _RO_CUSTOMER_NAME ON _RO_CUSTOMER_NAME.COMBINATION_ID = RO.ID
INNER JOIN REFERENCE_OBJECT _CUSTOMER_NAME ON _CUSTOMER_NAME.ID = _RO_CUSTOMER_NAME.SUBORDINATE_ID AND _CUSTOMER_NAME.DIMENSION_ID = 5
INNER JOIN REFERENCE_OBJECT_HIERARCHY _CUSTOMER_NAME_NATION ON _CUSTOMER_NAME_NATION.CHILD_ID = _CUSTOMER_NAME.ID
INNER JOIN REFERENCE_OBJECT _NATION ON _NATION.ID = _CUSTOMER_NAME_NATION.PARENT_ID AND _NATION.DIMENSION_ID = 3
INNER JOIN REFERENCE_OBJECT_HIERARCHY _NATION_REGION ON _NATION_REGION.CHILD_ID = _NATION.ID
INNER JOIN REFERENCE_OBJECT _REGION ON _REGION.ID = _NATION_REGION.PARENT_ID AND _REGION.DIMENSION_ID = 2 AND _REGION.NAME = "EUROPE"
INNER JOIN REFERENCE_OBJECT_HIERARCHY _MONTH_YEAR ON _MONTH_YEAR.CHILD_ID = _MONTH.ID
INNER JOIN REFERENCE_OBJECT _YEAR ON _YEAR.ID = _MONTH_YEAR.PARENT_ID AND _YEAR.DIMENSION_ID = 17 AND _YEAR.NAME = "1998"
INNER JOIN FACT REVENUE ON REVENUE.REFERENCE_OBJECT_ID = RO.ID AND REVENUE.RATIO_ID = 1
WHERE RO.DIMENSION_ID IN(20);

#Q1.2



