USE TPCH_SMALL_STAR;
SET @SF := 1;
#Q1.1
SELECT C_R_NAME, D_YEAR_NUMBER, SUM(REVENUE), SUM(PRODUCT_COST), SUM(PROFIT), SUM(SELLING_PRICE) FROM FACT F
    INNER JOIN DIM_CUSTOMER C ON C.PK_CUSTOMER = F.FK_CUSTOMER
    INNER JOIN DIM_DATE D ON D.DATE_PK = F.FK_ORDERDATE
WHERE C_R_NAME = "EUROPE"
  AND D.D_YEAR_NUMBER = 1998;


#Q2.1
SELECT C_MKTSEGMENT, D_MONTH_NUMBER, D_YEAR_NUMBER, SUM(PROFIT), SUM(L_QUANTITY) FROM FACT F
    INNER JOIN DIM_CUSTOMER C ON C.PK_CUSTOMER = F.FK_CUSTOMER
    INNER JOIN DIM_DATE D ON D.DATE_PK = F.FK_ORDERDATE
WHERE C_MKTSEGMENT = "AUTOMOBILE"
  AND D_MONTH_NUMBER = 12
  AND D_YEAR_NUMBER = 1995;


# Q2.2
SELECT C_MKTSEGMENT, D_MONTH_NUMBER, D_YEAR_NUMBER, SUM(PROFIT), SUM(L_QUANTITY) FROM FACT F
    INNER JOIN DIM_CUSTOMER C ON C.PK_CUSTOMER = F.FK_CUSTOMER
    INNER JOIN DIM_DATE D ON D.DATE_PK = F.FK_ORDERDATE
WHERE (C_MKTSEGMENT = "AUTOMOBILE"
    OR C_MKTSEGMENT = "FURNITURE"
    OR C_MKTSEGMENT = "MACHINERY")
  AND (D_MONTH_NUMBER = 3
    OR D_MONTH_NUMBER = 6
    OR D_MONTH_NUMBER = 12)
  AND D_YEAR_NUMBER = 1994
GROUP BY C_MKTSEGMENT,D_MONTH_NUMBER,D_YEAR_NUMBER
HAVING SUM(L_QUANTITY) >= 4000*@SF;


#Q3.1
SELECT C_N_NAME, P_TYPE, D_YEAR_NUMBER, SUM(PRODUCT_COST),SUM(PROFIT),SUM(SELLING_PRICE) FROM FACT F
    INNER JOIN DIM_CUSTOMER C ON C.PK_CUSTOMER = F.FK_CUSTOMER
    INNER JOIN DIM_PRODUCT P ON P.PK_PART = F.FK_PART
    INNER JOIN DIM_DATE D ON D.DATE_PK = F.FK_ORDERDATE
WHERE C_N_NAME = "BRAZIL"
  AND P_TYPE = "SMALL PLATED TIN"
  AND D_YEAR_NUMBER = 1997;


#Q3.2
SELECT C_N_NAME, P_TYPE, D_YEAR_NUMBER, SUM(PRODUCT_COST),SUM(PROFIT),SUM(SELLING_PRICE) FROM FACT F
    INNER JOIN DIM_CUSTOMER C ON C.PK_CUSTOMER = F.FK_CUSTOMER
    INNER JOIN DIM_PRODUCT P ON P.PK_PART = F.FK_PART
    INNER JOIN DIM_DATE D ON D.DATE_PK = F.FK_ORDERDATE
WHERE P_TYPE = "PROMO POLISHED COPPER"
  AND D_YEAR_NUMBER BETWEEN 1993 AND 1996
GROUP BY C_N_NAME,P_TYPE,D_YEAR_NUMBER;


#Q3.3
SELECT C_N_NAME, P_TYPE, D_YEAR_NUMBER, SUM(PRODUCT_COST), SUM(PROFIT), SUM(SELLING_PRICE) FROM FACT F
    INNER JOIN DIM_CUSTOMER C ON C.PK_CUSTOMER = F.FK_CUSTOMER
    INNER JOIN DIM_PRODUCT P ON P.PK_PART = F.FK_PART
    INNER JOIN DIM_DATE D ON D.DATE_PK = F.FK_ORDERDATE
WHERE (C_N_NAME = "BRAZIL"
    OR C_N_NAME = "UNITED STATES"
    OR C_N_NAME = "JAPAN")
  AND (P_TYPE = "LARGE ANODIZED NICKEL"
    OR P_TYPE = "LARGE ANODIZED STEEL"
    OR P_TYPE = "LARGE ANODIZED TIN")
  AND D_YEAR_NUMBER = 1995
GROUP BY C_N_NAME,P_TYPE,D_YEAR_NUMBER
ORDER BY C_N_NAME,P_TYPE,D_YEAR_NUMBER;


#Q4.1
SELECT O_CLERK, P_MFGR, D_YEAR_NUMBER, SUM(REVENUE), SUM(PROFIT) FROM FACT F
    INNER JOIN DIM_CLERK K ON K.PK_CLERK = F.FK_CLERK
    INNER JOIN DIM_PRODUCT P ON P.PK_PART = F.FK_PART
    INNER JOIN DIM_DATE D ON D.DATE_PK = F.FK_ORDERDATE
WHERE O_CLERK = "CLERK#000000015"
  AND (P_MFGR = "MANUFACTURER#2"
    OR P_MFGR ="MANUFACTURER#5")
  AND D_YEAR_NUMBER = 1993;


#Q5.1
SELECT C_R_NAME,P_MFGR,D_MONTH_NUMBER,D_YEAR_NUMBER, SUM(REVENUE) FROM FACT F
    INNER JOIN DIM_CUSTOMER C ON C.PK_CUSTOMER = F.FK_CUSTOMER
    INNER JOIN DIM_PRODUCT P ON P.PK_PART = F.FK_PART
    INNER JOIN DIM_DATE D ON D.DATE_PK = F.FK_ORDERDATE
WHERE P_MFGR = "MANUFACTURER#4"
  AND D_MONTH_NUMBER = 11
  AND D_YEAR_NUMBER = 1992
GROUP BY C_R_NAME,P_MFGR,D_MONTH_NUMBER,D_YEAR_NUMBER;


#Q5.2
SELECT C_R_NAME,P_MFGR,D_MONTH_NUMBER,D_YEAR_NUMBER, SUM(REVENUE) FROM FACT F
    INNER JOIN DIM_CUSTOMER C ON C.PK_CUSTOMER = F.FK_CUSTOMER
    INNER JOIN DIM_PRODUCT P ON P.PK_PART = F.FK_PART
    INNER JOIN DIM_DATE D ON D.DATE_PK = F.FK_ORDERDATE
WHERE (P_MFGR = "MANUFACTURER#1"
    OR P_MFGR = "MANUFACTURER#3")
  AND D_YEAR_NUMBER >= 1996
GROUP BY C_R_NAME,P_MFGR,D_MONTH_NUMBER,D_YEAR_NUMBER;


#Q6.1
SELECT C_MKTSEGMENT,P_TYPE,S_NAME,D_YEAR_NUMBER, SUM(PRODUCT_COST), SUM(SELLING_PRICE), SUM(L_QUANTITY) FROM FACT F
    INNER JOIN DIM_CUSTOMER C ON C.PK_CUSTOMER = F.FK_CUSTOMER
    INNER JOIN DIM_PRODUCT P ON P.PK_PART = F.FK_PART
    INNER JOIN DIM_SUPPLIER S ON S.PK_SUPPLIER = F.FK_SUPPLIER
    INNER JOIN DIM_DATE D ON D.DATE_PK = F.FK_ORDERDATE
WHERE C_MKTSEGMENT = "MACHINERY"
  AND S_NAME = "SUPPLIER#000000093"
  AND D_YEAR_NUMBER BETWEEN 1995 AND 1997
GROUP BY C_MKTSEGMENT,P_TYPE,S_NAME,D_YEAR_NUMBER
ORDER BY C_MKTSEGMENT,P_TYPE,S_NAME,D_YEAR_NUMBER;


#Q7.1
SELECT C_NAME,P_BRAND,D_MONTH_NUMBER,D_YEAR_NUMBER, SUM(L_QUANTITY) FROM FACT F
    INNER JOIN DIM_CUSTOMER C ON C.PK_CUSTOMER = F.FK_CUSTOMER
    INNER JOIN DIM_PRODUCT P ON P.PK_PART = F.FK_PART
    INNER JOIN DIM_DATE D ON D.DATE_PK = F.FK_ORDERDATE
WHERE C_NAME = "CUSTOMER#000000854"
GROUP BY C_NAME,P_BRAND,D_MONTH_NUMBER,D_YEAR_NUMBER
ORDER BY C_NAME,P_BRAND,D_MONTH_NUMBER,D_YEAR_NUMBER;


#Q7.2
SELECT C_NAME,P_BRAND,D_MONTH_NUMBER,D_YEAR_NUMBER, SUM(L_QUANTITY) FROM FACT F
    INNER JOIN DIM_CUSTOMER C ON C.PK_CUSTOMER = F.FK_CUSTOMER
    INNER JOIN DIM_PRODUCT P ON P.PK_PART = F.FK_PART
    INNER JOIN DIM_DATE D ON D.DATE_PK = F.FK_ORDERDATE
WHERE C_NAME = "CUSTOMER#000000854"
GROUP BY C_NAME,P_BRAND,D_MONTH_NUMBER,D_YEAR_NUMBER
HAVING SUM(L_QUANTITY) >= 30*@SF
ORDER BY C_NAME,P_BRAND,D_MONTH_NUMBER,D_YEAR_NUMBER;


#Q8.1
SELECT O_CLERK,C_R_NAME,C_MKTSEGMENT, SUM(REVENUE),SUM(PRODUCT_COST),SUM(PROFIT),SUM(SELLING_PRICE),SUM(L_QUANTITY) FROM FACT F
    INNER JOIN DIM_CLERK K ON K.PK_CLERK = F.FK_CLERK
    INNER JOIN DIM_CUSTOMER C ON C.PK_CUSTOMER = F.FK_CUSTOMER
WHERE O_CLERK = "CLERK#000000535"
  AND C_MKTSEGMENT = "FURNITURE"
GROUP BY O_CLERK,C_R_NAME,C_MKTSEGMENT
ORDER BY O_CLERK,C_R_NAME,C_MKTSEGMENT;


#Q9.1
SELECT C_N_NAME,C_MKTSEGMENT,S_NAME, SUM(REVENUE), SUM(PRODUCT_COST), SUM(SELLING_PRICE) FROM FACT F
    INNER JOIN DIM_CUSTOMER C ON C.PK_CUSTOMER = F.FK_CUSTOMER
    INNER JOIN DIM_SUPPLIER S ON S.PK_SUPPLIER = F.FK_SUPPLIER
WHERE S.S_NAME = "SUPPLIER#000000024"
  AND (C.C_N_NAME = "CANADA"
    OR C.C_N_NAME = "UNITED STATES")
GROUP BY C_N_NAME,C_MKTSEGMENT,S_NAME
ORDER BY C_N_NAME,C_MKTSEGMENT,S_NAME;


#Q10.1
SELECT O_CLERK, P_BRAND,P_NAME, SUM(PROFIT),SUM(L_QUANTITY) FROM FACT F
    INNER JOIN DIM_PRODUCT P ON P.PK_PART = F.FK_PART
    INNER JOIN DIM_CLERK K ON K.PK_CLERK = F.FK_CLERK
WHERE P_BRAND = "BRAND#41"
GROUP BY O_CLERK, P_BRAND, P_NAME
HAVING SUM(PROFIT) < 0
ORDER BY O_CLERK,P_BRAND,P_NAME;


#Q10.2
SELECT P_BRAND, P_NAME, SUM(PROFIT), SUM(L_QUANTITY) FROM FACT F
    INNER JOIN DIM_PRODUCT P ON P.PK_PART = F.FK_PART
GROUP BY P_BRAND, P_NAME
HAVING SUM(PROFIT) < 0
ORDER BY SUM(PROFIT);

