# Q1.1:

SELECT C_R_NAME, D_YEAR_NUMBER, SUM(REVENUE) FROM FACT F
    INNER JOIN DIM_CUSTOMER C ON C.PK_CUSTOMER = F.FK_CUSTOMER
    INNER JOIN DIM_DATE D ON D.DATE_PK = F.FK_ORDERDATE
WHERE C_R_NAME = "EUROPE" AND D.D_YEAR_NUMBER = 1998;

# Q1.2:

SELECT C_R_NAME, D_YEAR_NUMBER, SUM(REVENUE) FROM FACT F
    INNER JOIN DIM_CUSTOMER C ON C.PK_CUSTOMER = F.FK_CUSTOMER
    INNER JOIN DIM_DATE D ON D.DATE_PK = F.FK_ORDERDATE
WHERE (C_R_NAME = "AFRICA" OR C_R_NAME = "ASIA")
  AND D.D_YEAR_NUMBER BETWEEN 1994 AND 1995;

#...